add transfer file feature
test-fullautomation/robotframework-qconnect-base pull request #33
Opened 2023-08-25 08:28 UTC by milanac030988

2023-08-25 10:23 UTC, test-fullautomation requested changes
Hi Cuong,
please check my findings.
Thank you,
 Thomas

2023-08-25 10:23 UTC, test-fullautomation commented on setup_call.bat
Hi Cuong,

uups, this file is not supposed to be here.
Please fix.

Thank you,
 Thomas

2023-08-28 08:21 UTC, milanac030988 commented on setup_call.bat
Hello Thomas,

I've removed.

Thank you, 
Cuong

2023-08-28 09:27 UTC, test-fullautomation requested changes

2023-08-28 09:27 UTC, test-fullautomation commented on setup_call.bat
Hi Cuong,
setup_call.bat is still there?
Please fix.
Thank you,
 Thomas

2023-08-28 09:53 UTC, milanac030988 commented on setup_call.bat
Hello Thomas,

Sorry that I've committed wrong repo.
It has been deleted now.

Thank you,
Cuong

2023-08-28 11:14 UTC, test-fullautomation approved these changes
Hi Cuong,
looks good to me!
Thank you,
 Thomas

2023-08-28 11:17 UTC, merged